language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install pytest-flake8 pytest-pep257
  - pip install .
# command to run tests
script: py.test --flake8 --pep257 -s tests
branches:
  only:
    - master
