language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7dev"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install pytest-flake8 pytest-pep257
  - pip install .
# command to run tests
script: pytest --flake8 --pep257 -s tests
branches:
  only:
    - master
    - wordlists
