dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

install:
  - pip install pip==18.1
  - pip install -r requirements.txt -r requirements.test.txt .
script: pytest -c pytest.full.ini
