sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install -U pip==18.0
  - pip install tox-travis .
# command to run tests
script: tox
branches:
  only:
    - master
